// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwhxxqgtbuoxvqqaxbfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3aHh4cWd0YnVveHZxcWF4YmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNTA5MTUsImV4cCI6MjA3MzgyNjkxNX0.RdCsSlPuyfQlVMq1KKJrjws57YC-YC8EgN5lH68Ch2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});